apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: volume-bot
  labels:
    app: volume-bot
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volume-bot
      component: api
  template:
    metadata:
      labels:
        app: volume-bot
        component: api
    spec:
      containers:
      - name: api
        image: volume-bot-api:latest  # Replace with your image registry
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        # ConfigMap values
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: NODE_ENV
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: API_PORT
        - name: OTEL_ENABLED
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: OTEL_ENABLED
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: OTEL_SERVICE_NAME
        - name: SENTRY_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: SENTRY_ENVIRONMENT
        - name: SENTRY_TRACES_SAMPLE_RATE
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: SENTRY_TRACES_SAMPLE_RATE
        # Secret values
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: REDIS_URL
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: MASTER_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: MASTER_ENCRYPTION_KEY
        - name: SOLANA_RPC_URL
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SOLANA_RPC_URL
        - name: RPC_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: RPC_ENDPOINT
        - name: RPC_WEBSOCKET_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: RPC_WEBSOCKET_ENDPOINT
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SENTRY_DSN
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              optional: true
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 3001
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: volume-bot
  labels:
    app: volume-bot
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: volume-bot
    component: api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: volume-bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
