version: '3.9'

services:
  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: boggy-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - boggy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: boggy-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"
    environment:
      # Node Environment
      - NODE_ENV=production

      # API Configuration
      - API_PORT=${API_PORT:-3001}
      - API_HOST=${API_HOST:-0.0.0.0}

      # Database (Supabase)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}

      # Redis
      - REDIS_URL=redis://redis:6379

      # Solana
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_RPC_WSS_URL=${SOLANA_RPC_WSS_URL}

      # Security
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}

      # Monitoring (Optional)
      - SENTRY_DSN=${SENTRY_DSN:-}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}

    depends_on:
      redis:
        condition: service_healthy
    networks:
      - boggy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${API_PORT:-3001}/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Workers Service
  workers:
    build:
      context: .
      dockerfile: Dockerfile
      target: workers
    container_name: boggy-workers
    restart: unless-stopped
    environment:
      # Node Environment
      - NODE_ENV=production

      # Database (Supabase)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}

      # Redis
      - REDIS_URL=redis://redis:6379

      # Solana
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_RPC_WSS_URL=${SOLANA_RPC_WSS_URL}

      # Security
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}

      # Jito (if used)
      - JITO_BLOCK_ENGINE_URL=${JITO_BLOCK_ENGINE_URL:-}
      - JITO_AUTH_KEYPAIR=${JITO_AUTH_KEYPAIR:-}

      # Monitoring (Optional)
      - SENTRY_DSN=${SENTRY_DSN:-}

    depends_on:
      redis:
        condition: service_healthy
    networks:
      - boggy-network

networks:
  boggy-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
