apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: volume-bot
  labels:
    app: volume-bot
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volume-bot
      component: worker
  template:
    metadata:
      labels:
        app: volume-bot
        component: worker
    spec:
      containers:
      - name: worker
        image: volume-bot-worker:latest  # Replace with your image registry
        imagePullPolicy: Always
        env:
        # ConfigMap values
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: NODE_ENV
        - name: WORKER_CONCURRENCY
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: WORKER_CONCURRENCY
        - name: STATUS_AGGREGATOR_INTERVAL_SECONDS
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: STATUS_AGGREGATOR_INTERVAL_SECONDS
        - name: SENTRY_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: SENTRY_ENVIRONMENT
        - name: BUY_LOWER_AMOUNT
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: BUY_LOWER_AMOUNT
        - name: BUY_UPPER_AMOUNT
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: BUY_UPPER_AMOUNT
        - name: BUY_INTERVAL_MIN
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: BUY_INTERVAL_MIN
        - name: BUY_INTERVAL_MAX
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: BUY_INTERVAL_MAX
        - name: DISTRIBUTE_WALLET_NUM
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: DISTRIBUTE_WALLET_NUM
        - name: SELL_ALL_BY_TIMES
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: SELL_ALL_BY_TIMES
        - name: JITO_FEE
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: JITO_FEE
        - name: BLOCKENGINE_URL
          valueFrom:
            configMapKeyRef:
              name: volume-bot-config
              key: BLOCKENGINE_URL
        # Secret values
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: REDIS_URL
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: MASTER_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: MASTER_ENCRYPTION_KEY
        - name: SOLANA_RPC_URL
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SOLANA_RPC_URL
        - name: RPC_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: RPC_ENDPOINT
        - name: RPC_WEBSOCKET_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: RPC_WEBSOCKET_ENDPOINT
        - name: JITO_KEY
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: JITO_KEY
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: volume-bot-secrets
              key: SENTRY_DSN
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pgrep -f "node dist/main.js"
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pgrep -f "node dist/main.js"
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: volume-bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
